[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
    from = "/api"
    to = "https://api.steampowered.com"

[[redirects]]
    from = "/store"
    to = "https://store.steampowered.com"
